Revert "Verify sign-off email address against committer email field"
This reverts commit 7c507e80e0021f2250c502f35f8c7fb1b89c2cc5.

```
AttributeError: 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "/opt/prassign/assign-pull-requests.py", line 421, in <module>
    sys.exit(main(*sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^^
  File "/opt/prassign/assign-pull-requests.py", line 124, in main
    assign_one(pr_getter, issue, dev_mapping, proj_mapping, categories,
  File "/opt/prassign/assign-pull-requests.py", line 372, in assign_one
    missing_signoff = not all(commit_contains_correct_signoff(c) for c in pr.get_commits())
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/prassign/assign-pull-requests.py", line 372, in <genexpr>
    missing_signoff = not all(commit_contains_correct_signoff(c) for c in pr.get_commits())
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/prassign/assign-pull-requests.py", line 142, in commit_contains_correct_signoff
    committer_email = commit.committer.email.lower()  # case insensitive
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'
```

Bug: https://github.com/projg2/assign-pull-requests/issues/5
Signed-off-by: Sam James <sam@gentoo.org>